### ISSUE TITLE
.endsWith of undefined

### ISSUE THREAD

**Issue by marutypes** [lemonmade/sewing-kit#44]
I'm getting an unhandled promise rejection which doesn't seem to stop builds from finishing but does break reporting for the last output of my project. 

This is reproducible in a minimal project with just an `src/index.ts`, `package.json`, and a `sewing-kit.config.js` that looks like:

```js
import {createPackage} from '@sewing-kit/config';
import {javascript} from '@sewing-kit/plugin-javascript';
import {typescript} from '@sewing-kit/plugin-typescript';
import {eslint} from '@sewing-kit/plugin-eslint';
import {jest} from '@sewing-kit/plugin-jest';
import {buildFlexibleOutputs} from '@sewing-kit/plugin-package-flexible-outputs';

export default createPackage((pkg) => {
  pkg.entry('src/index');
  pkg.use(javascript(), typescript(), jest(), eslint(), buildFlexibleOutputs());
});
```
![image](https://user-images.githubusercontent.com/4889856/86952234-b059a280-c120-11ea-93d4-b5553470b71a.png)

Here's what I get as output
![image](https://user-images.githubusercontent.com/4889856/86952434-fdd60f80-c120-11ea-9d9c-23a2198e8030.png)

**Comment by marutypes** [comment]
note: I get this promise rejection even when I remove every plugin and build target one by one, I can't figure out if any particular one is causing it, and the src it points to seems to be coming from an `fs` module? Might look into it more later.

**Comment by ismail-syed** [comment]
Moved to https://github.com/Shopify/sewing-kit-next/issues/40
