### ISSUE TITLE
--watch is not supported without git/hg

### ISSUE THREAD

**Issue by marutypes** [lemonmade/sewing-kit#45]
I have the following SK config, and a minimal project with only a `index.ts` and an `index.test.ts`, and when I run `yarn test` I get an error message back from jest.

```
import {createPackage} from '@sewing-kit/config';
import {javascript} from '@sewing-kit/plugin-javascript';
import {typescript} from '@sewing-kit/plugin-typescript';
import {eslint} from '@sewing-kit/plugin-eslint';
import {jest} from '@sewing-kit/plugin-jest';
import {buildFlexibleOutputs} from '@sewing-kit/plugin-package-flexible-outputs';

export default createPackage((pkg) => {
  pkg.entry('src/index');
  pkg.use(javascript(), typescript(), jest(), eslint(), buildFlexibleOutputs());
});
```

`yarn test <something>` works as expected

![image](https://user-images.githubusercontent.com/4889856/86952654-52798a80-c121-11ea-9804-d0bf7d0852f9.png)

**Comment by marutypes** [comment]
I think we can get around this by automatically using `watchAll` instead of `watch` when no pattern is supplied.

**Comment by marutypes** [comment]
**update**: `not supported without git/hg` means that it only works when git has been properly initialized.. I am fool

We could probably make a better errormessage or default to `watchAll` in that case though. It would be nice to save others the confusion.

**Comment by ismail-syed** [comment]
Moved to https://github.com/Shopify/sewing-kit-next/issues/41
