### ISSUE TITLE
Module mapper regex sometimes not specific enough

### ISSUE THREAD

**Issue by b-ryu** [lemonmade/sewing-kit#56]
I came across this issue earlier on when migrating over Quilt. I think it stems from the fact that the `moduleNameMapper` in the Jest configs has regex that may match several modules at once.

_`.sewing-kit/config/jest/root.config.js`_
<img width="720" alt="Screen Shot 2020-08-19 at 11 16 05 AM" src="https://user-images.githubusercontent.com/46533681/90653688-7d212d80-e20d-11ea-8d74-90ab1859779c.png">

### Example

My scenario was that in order to support repo-level tests (tests not tied to a specific package), I had placed a `sewing-kit.config.ts` in my local `test` folder and made it a "package" that SK-next could run tests for. This placed it in the `moduleNameMapper` like so:

_`.sewing-kit/config/jest/root.config.js`_
<img width="683" alt="Screen Shot 2020-08-19 at 11 29 32 AM" src="https://user-images.githubusercontent.com/46533681/90655221-4c41f800-e20f-11ea-889e-679e4cf183a3.png">

However elsewhere in our code we were importing from a third-party lib `supertest`. `supertest` matches the regex `test$`, so instead of importing from `node_modules/supertest` it instead tried to import from our local `test` module and thus caused an error.

<img width="792" alt="Screen Shot 2020-08-19 at 12 13 40 PM" src="https://user-images.githubusercontent.com/46533681/90661899-ba89b900-e215-11ea-9c06-a540690b07f9.png">

(You can repro for yourself by going to [this Quilt branch](https://github.com/Shopify/quilt/tree/sk-next-supertest-conflict-example) and running `yarn sk test react-server`. You can also go to `node_modules/@sewing-kit/plugin-jest/build/cjs/plugin-jest.js` and fix the regex and see how that changes the test behaviour.)

---

This example is no longer relevant to us now, since we've since gotten rid of `supertest` and I found a better way of running non-package tests without adding an extra `sewing-kit.config.ts`, but this may be an issue for other folks. Say, if:
- Someone has a workspace with a local package called `package-name`
- They import from a third-party lib called `third-party-package-name` in a test
- The module map will try and resolve `third-party-package-name` to the local `package-name` in tests, since `third-party-package-name` matches the regex `package-name$`

The immediate solution that comes to mind is just adding `^` to the beginning of that regex to match module names exactly, not sure if that'll have unintended consequences however.

**Comment by lemonmade** [comment]
Agreed that there is an issue here (will review the PR), but I'm glad you found an alternative to a "fake" package here, as I think we would want people to avoid those kinds of approaches that break the workspace model in sewing kit.
