### ISSUE TITLE
Make esmodules plugin output the correct package.json entries for true node ES support

### ISSUE THREAD

**Issue by lemonmade** [lemonmade/sewing-kit#7]
https://2ality.com/2019/10/hybrid-npm-packages.html?utm_campaign=Feed%3A+2ality+%282ality+–+JavaScript+and+more%29&utm_medium=feed&utm_source=feedburner

**Comment by ismail-syed** [comment]
Moved over to https://github.com/Shopify/sewing-kit-next/issues/8
